[package]
name = "gamma-table-macros"
version = "0.1.0"
authors = ["Christopher B. Liebman <liebman@zod.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A procedural macro for generating gamma correction lookup tables"
repository = "https://github.com/liebman/gamma-table-macros"
documentation = "https://docs.rs/gamma-table-macros"
keywords = ["gamma", "correction", "lookup-table", "proc-macro", "graphics"]
categories = ["graphics", "algorithms", "development-tools::procedural-macro-helpers"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
trybuild = "1.0" 

# Coverage configuration
[package.metadata.coverage.run]
include-ffi = false
skip-clean = false

[package.metadata.coverage.report]
# Exclude generated files and test modules from coverage
exclude = [
    "*/target/*",
    "*/tests/*",
    "*/benches/*",
]
